### ISSUE TITLE
TypeError: FPDF.set_fill_color() takes from 2 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by mohindra9211** [py-pdf/fpdf2#1038] opened 2023-11-28 09:13 UTC
I found an error in FPDF.set_fill_color(), please give me some solution about it

```python
from fpdf import FPDF
from fpdf.fonts import FontFace

class FPDF(FPDF):
    def set_dark_green_title(self, title):
        self.set_fill_color(0, 128, 0)  # Dark green color
        self.set_text_color(255, 255, 255)  # White text color
        self.set_font("Times", "B", 16)
        self.cell(0, 10, title, 1, 1, 'L', 1)
        self.ln(5)  # Add some space after the title

# Create instance of FPDF class
pdf = FPDF()
pdf.add_page()

pdf.set_dark_green_title("Title1")
pdf.set_text_color(0, 0, 0)  # Reset text color to black    
pdf.multi_cell(0, 10, "This is the content for Title 1.")
pdf.ln(5)
pdf.set_dark_green_title("Title2")
pdf.set_text_color(0, 0, 0)  # Reset text color to black
pdf.multi_cell(0, 10, "This is the content for Title 2.")
pdf.ln(5)
pdf.set_dark_green_title("Title3")
pdf.set_text_color(0, 0, 0)  # Reset text color to black
pdf.multi_cell(0, 10, "This is the content for Title 3.")
pdf.ln(5)

# table content

TABLE_DATA = (
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
    ("Mary", "Ramos", "45", "Orlando"),
    ("Carlson", "Banks", "19", "Los Angeles"),
    ("Lucas", "Cimon", "31", "Saint-Mahturin-sur-Loire"),
)

pdf.set_font("Times", size=10)
blue = (0, 0, 255)
grey = (128, 128, 128)
headings_style = FontFace(emphasis="ITALICS", color=blue, fill_color=grey)
with pdf.table(headings_style=headings_style) as table:
    for data_row in TABLE_DATA:
        row = table.row()
        for datum in data_row:
            row.cell(datum)
            



# Save the pdf with name .pdf
pdf.output("output.pdf")
```

```
# ================================ Error ================================= 

------------------------------------------------------------------------
TypeError                              Traceback (most recent call last)
Cell In[18], line 43
     41 grey = (128, 128, 128)
     42 #headings_style = FontFace(emphasis="ITALICS", color=blue, fill_color=grey)
---> 43 with pdf.table() as table:
     44     for data_row in TABLE_DATA:
     45         row = table.row()

File C:\ProgramData\anaconda3\Lib\contextlib.py:144, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    142 if typ is None:
    143     try:
--> 144         next(self.gen)
    145     except StopIteration:
    146         return False

File ~\AppData\Roaming\Python\Python311\site-packages\fpdf\fpdf.py:4883, in FPDF.table(self, *args, **kwargs)
   4881 table = Table(self, *args, **kwargs)
   4882 yield table
-> 4883 table.render()

File ~\AppData\Roaming\Python\Python311\site-packages\fpdf\table.py:266, in Table.render(self)
    264     elif i and self._gutter_height:
    265         self._fpdf.y += self._gutter_height
--> 266     self._render_table_row(
    267         i, row_layout_info, cell_x_positions=cell_x_positions
    268     )
    269 # Restoring altered FPDF settings:
    270 self._fpdf.l_margin = prev_l_margin

File ~\AppData\Roaming\Python\Python311\site-packages\fpdf\table.py:333, in Table._render_table_row(self, i, row_layout_info, cell_x_positions, fill, **kwargs)
    330 y = self._fpdf.y  # remember current y position, reset after each cell
    332 for cell in row.cells:
--> 333     self._render_table_cell(
    334         i,
    335         j,
    336         cell,
    337         row_height=self._line_height,
    338         cell_height_info=row_layout_info,
    339         cell_x_positions=cell_x_positions,
    340         fill=fill,
    341         **kwargs,
    342     )
    343     j += cell.colspan
    344     self._fpdf.set_y(y)  # restore y position after each cell

File ~\AppData\Roaming\Python\Python311\site-packages\fpdf\table.py:443, in Table._render_table_cell(self, i, j, cell, row_height, fill, cell_height_info, cell_x_positions, **kwargs)
    438 x2 = (
    439     x1 + col_width
    440 )  # already includes gutter for cells spanning multiple columns
    441 y2 = y1 + cell_height
--> 443 draw_box_borders(
    444     self._fpdf,
    445     x1,
    446     y1,
    447     x2,
    448     y2,
    449     border=self.get_cell_border(i, j),
    450     fill_color=style.fill_color if fill else None,
    451 )
    453 # draw outer box if needed
    455 if self._outer_border_width:

File ~\AppData\Roaming\Python\Python311\site-packages\fpdf\table.py:25, in draw_box_borders(pdf, x1, y1, x2, y2, border, fill_color)
     23     if isinstance(fill_color, (int, float)):
     24         fill_color = [fill_color]
---> 25     pdf.set_fill_color(*fill_color)
     27 sl = []
     29 k = pdf.k

TypeError: FPDF.set_fill_color() takes from 2 to 4 positional arguments but 5 were given

```

**Comment by blaketeres** [comment] 2023-11-28 15:44
Having the same issue.

**Comment by blaketeres** [comment] 2023-11-28 17:01
A quick fix for me was to add this method to my class. Looks like something is passing RGBA values normalized in the range 0-1 (rather than 0-255) to `set_fill_color`.

```python
from fpdf import FPDF


class MyPDF(FPDF):
    def set_fill_color(self, *args, **kwargs):
        try:
            super().set_fill_color(*args, **kwargs)
        except Exception:
            super().set_fill_color(*[x * 255 for x in args[:3]])
```

**Comment by Lucas-C** [comment] 2023-11-28 19:13
What version of `fpdf2` are you using @blaketeres & @mohindra9211?
You can see it by running `pip freeze`

And have you checked if this bug is still present when using the latest version from the `master` branch of this repo?
You can install it this way:

    pip install git+https://github.com/py-pdf/fpdf2.git@master

I think this may be a duplicate of #963 fixed by #964

**Comment by mohindra9211** [comment] 2023-11-29 07:48
> What version of `fpdf2` are you using @blaketeres & @mohindra9211? You can see it by running `pip freeze`
> 
> And have you checked if this bug is still present when using the latest version from the `master` branch of this repo? You can install it this way:
> 
> ```
> pip install git+https://github.com/py-pdf/fpdf2.git@master
> ```
> 
> I think this may be a duplicate of #963 fixed by #964

I am using FPDF2 version 2.7.6

**Comment by Lucas-C** [comment] 2023-11-29 10:37
> I am using FPDF2 version 2.7.6

OK, then you are very likely affected by this bug that has been resolved.

Have you tried installing the latest version of `fpdf2` from the `master` branch?

I tested @mohindra9211 code and with this latest version, there is **no error raised**.

**Comment by blaketeres** [comment] 2023-12-01 17:55
Yep, works when using `master` branch. Thanks for the response and I'll await the next release.

**Comment by mohindra9211** [comment] 2023-12-02 13:48
> > I am using FPDF2 version 2.7.6
> 
> OK, then you are very likely affected by this bug that has been resolved.
> 
> Have you tried installing the latest version of `fpdf2` from the `master` branch?
> 
> I tested @mohindra9211 code and with this latest version, there is **no error raised**.

Thanks for solving this issue and please update it to the latest version of fpdf2.

**Comment by Lucas-C** [comment] 2023-12-04 11:20
Thank you for your feedbacks

Now closing this

**Closed by Lucas-C** 2023-12-04 11:20 UTC
Labels: bug, duplicate, pending-answer
