### ISSUE TITLE
set_fill_colour() error when creating tables in 2.7.6

### ISSUE THREAD

**Issue by ajuava** [py-pdf/fpdf2#991] opened 2023-10-29 00:01 UTC
When attempting to create a new table in the 2.7.6 update, it raises the following error: 
```python
  File "C:\Users\***\PycharmProjects\***\reporting.py", line 252, in on_generate_clicked
    generator.generate_pdf(self.client_data, self.report_data, self.le_report_id.text(), self.chk_phoned.isChecked(), self.chk_approved.isChecked(), self.files_list)
  File "C:\Users\***\PycharmProjects\***\reporting.py", line 261, in generate_pdf
    self.add_defaults(pdf, client_info_values, report_info_values, phoned, approved, attachments, report_id)
  File "C:\Users\***\PycharmProjects\***\reporting.py", line 796, in add_defaults
    row.cell(datum)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fpdf\fpdf.py", line 4883, in table
    table.render()
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fpdf\table.py", line 266, in render
    self._render_table_row(
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fpdf\table.py", line 333, in _render_table_row
    self._render_table_cell(
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fpdf\table.py", line 443, in _render_table_cell
    draw_box_borders(
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fpdf\table.py", line 25, in draw_box_borders
    pdf.set_fill_color(*fill_color)
TypeError: set_fill_color() takes from 2 to 4 positional arguments but 5 were given
```

**Minimal code**
```python
        with pdf.table() as table:
            test=(
    ("First name", "Last name", "Age", "City"),
    ("Jules", "Smith", "34", "San Juan"),
    ("Mary", "Ramos", "45", "Orlando"),
    ("Carlson", "Banks", "19", "Los Angeles"),
    ("Lucas", "Cimon", "31", "Saint-Mahturin-sur-Loire"),
)

            with pdf.table() as table:
                for data_row in test:
                    row = table.row()
                    for datum in data_row:
                        row.cell(datum)

...
```

I believe the issue lies with the fill colours that are being used, I modified table.py in fpdf2 with the following: `print("fill_color:", fill_color)
pdf.set_fill_color(*fill_color)` and it gave the output of: fill_color: DeviceRGB(r=1.0, g=1.0, b=1.0, a=None) which makes me think that it might be the alpha that has the issue?

I managed to fix the problem by modifying `pdf.set_fill_color(*fill_color)` to the following: `corrected_fill_color = (int(fill_color.r * 255), int(fill_color.g * 255), int(fill_color.b * 255))
        pdf.set_fill_color(*corrected_fill_color)`

but im not sure if this will have any further issues for other features

**Environment**
Please provide the following information:
* **Operating System**: Windows 11
* **Python version**: 3.8.10
* **`fpdf2` version used**: 2.7.6

_edit by gmischler: fixed traceback formatting_

**Comment by gmischler** [comment] 2023-10-29 10:47
Welcome to fpdf2, @ajuava, and thanks for the report.

It appears to be a duplicate of #963, so I'm going to close it.
The problem is being worked on in PR #964, which will hopefully be ready for the next release.

**Closed by gmischler** 2023-10-29 10:47 UTC
Labels: bug

**Comment by Lucas-C** [comment] 2023-11-09 08:01
> Hi @gmischler / @Lucas-C ! I'd like to ask if there are any timelines for when this might get fixed? I'm getting the same error and can see that this [PR](https://github.com/py-pdf/fpdf2/pull/964#ref-issue-1966776349) is still open. Thanks in advance

Thank you for the reminder.

I have just merged https://github.com/py-pdf/fpdf2/pull/964
