### ISSUE TITLE
HTML: indent of lists on new line not flush

### ISSUE THREAD

**Issue by xbln** [py-pdf/fpdf2#1212] opened 2024-06-22 01:15 UTC
`The` indentation of list items is not flush on a new line

Should be:

- ldflfdkl kfdkfklfgd kdfködf ureuztrt uret rteiui tr reoiouerioure uoerotuueroou perpt perpi. repiter p reip tepi. reiptrei perpt prer tperi tepri

But is:

`*  jfjkjkfjfd dflfdlflklkfd lkfdklfdklmf fdklfdklfd ldfklfdklfd lkdfklfkld dflkfdkldf ldfklkkldfl fdldflkfdklklfd ldflkfdlkdfl ldf df fd lldf ldfllkfdklfkl lkfdklfdkl kldfklfdlkfd lkdflkfdlkdflk lkdfkllkfdkfd ldfl fd `

Use of  tag_indents={"li": 5} doesn´t help
I checked also ver 2.7.10 (master), but no improvement

**Comment by gmischler** [comment] 2024-06-24 07:01
Welcome to fpdf2, @xbln !

As requested in the bug report template (that you summarily deleted instead of using it), please show us a minimal code example that produces the described result.

The explanation you gave us does not make it possible to reproduce the effect you're seeing.
And if we can't reproduce an error, then we can't fix it.

**Comment by Lucas-C** [comment] 2024-06-24 14:59
I agree with @gmischler, we need some SHORT code snippet to be able to help you 🙂

As mentioned in the [bug report template](https://github.com/py-pdf/fpdf2/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) that you must have seen, this page provides good explanation on how to craft a good minimal, reproducible example: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by xbln** [comment] 2024-06-24 15:31
Sorry, here is the code:

`from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.write_html("""
<p>Is:</p>
<ul>
    <li>Unordered list</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
</ul>
<ol>
    <li>Ordered list</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</li>
</ol>
Should be:
<ul>
    <li>Unordered list</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dolore magna aliqua. Ut enim ad minim veniam</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dolore magna aliqua. Ut enim ad minim veniam</li>
</ul>
<ol>
    <li>Ordered list</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dolore magna aliqua. Ut enim ad minim veniam</li>
    <li>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et<br>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;dolore magna aliqua. Ut enim ad minim veniam</li>
</ol>
""")
pdf.output("html.pdf")`

Output is:![image](https://github.com/py-pdf/fpdf2/assets/27554937/f2b13c20-208e-4801-b66d-e04aad14bd4a)

**Comment by gmischler** [comment] 2024-06-25 06:24
A few days ago #1170 has been merged, which fixes this (already reported in #1073).

Most likely your test with 2.7.10 (current HEAD) was just before that.
Can you try that again please?

**Comment by gmischler** [comment] 2024-07-11 07:05
Fixed in #1170.

**Closed by gmischler** 2024-07-11 07:05 UTC
Labels: bug, html, alignment
